giantswarm/cluster-api-provider-aws-app

helm/cluster-api-provider-aws/templates/infrastructure-secret.yaml, helm/cluster-api-provider-aws/values.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/16111
* fix secret key `credentials`
* add missing `[default]` section
* set values from installations
=> fix aws credentials

README.md
This sums up what we did today in order to create access for the CAPA controller.
=> WIP: prerequisites doc

helm/cluster-api-provider-aws/templates/infrastructure-secret.yaml
=> Remove duplicate base64 encoding

helm/cluster-api-provider-aws/ci/default-values.yaml, helm/cluster-api-provider-aws/values.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/16111
=> remove default credentials

README.md
=> use the WC account

README.md
=> fix some errors in the doc

helm/cluster-api-provider-aws/values.yaml
=> enable machinepools

helm/cluster-api-provider-aws/templates/infrastructure-deployment.yaml, helm/cluster-api-provider-aws/values.yaml
=> Update image to use fork with label filtering

helm/cluster-api-provider-aws/templates/_resource.tpl
Towards https://github.com/giantswarm/giantswarm/issues/16119
Let's test running multiple versions at the same time
=> dev version for dev release

helm/cluster-api-provider-aws/templates/infrastructure-deployment.yaml
=> disable leader election

helm/cluster-api-provider-aws/templates/webhook/webhook.yaml
=> Make sure mutation runs last

.circleci/config.yml, helm/cluster-api-provider-aws/ci/default-values.yaml, helm/cluster-api-provider-aws/templates/infrastructure-deployment.yaml, helm/cluster-api-provider-aws/templates/webhook/deployment.yaml, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/16080
=> update image for china testing

helm/cluster-api-provider-aws/Chart.yaml, helm/cluster-api-provider-aws/templates/_resource.tpl, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/16845
=> set version 0.6.5-gs1

helm/cluster-api-provider-aws/templates/infrastructure-deployment.yaml
Doing a demo I have found an error in the format
=> Set deployment annotations in right spot

CHANGELOG.md, helm/cluster-api-provider-aws/Chart.yaml, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/17493
=> CAPA version 0.6.6

CHANGELOG.md, helm/cluster-api-provider-aws/templates/ssh-sso-public-key-secret.yaml, helm/cluster-api-provider-aws/values.yaml
add secret that will contain installation ssh sso public key that will be used for bastion and node ssh access
=> add-secret-for-sso

helm/cluster-api-provider-aws/templates/ssh-sso-public-key-secret.yaml
=> add-labels-to-secretg

helm/cluster-api-provider-aws/ci/default-values.yaml, helm/cluster-api-provider-aws/values.yaml
=> move-ci-values

helm/cluster-api-provider-aws/values.yaml
=> add-service-type-label

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
=> Activated eks feature flags

README.md, helm/cluster-api-provider-aws/templates/ssh-sso-public-key-secret.yaml, helm/cluster-api-provider-aws/values.yaml
=> use workloadcluster instead of tenant

CHANGELOG.md, helm/cluster-api-provider-aws/templates/_helpers.tpl, helm/cluster-api-provider-aws/templates/eks/bootstrap/eks-bootstrap-deployment-webhook.yaml, helm/cluster-api-provider-aws/templates/eks/bootstrap/eks-bootstrap-deployment.yaml, helm/cluster-api-provider-aws/templates/eks/bootstrap/eks-bootstrap-service-webhook.yaml, helm/cluster-api-provider-aws/templates/eks/bootstrap/eks-bootstrap-service.yaml, helm/cluster-api-provider-aws/templates/eks/control-plane/eks-controlplane-deployment-webhook.yaml, helm/cluster-api-provider-aws/templates/eks/control-plane/eks-controlplane-deployment.yaml, helm/cluster-api-provider-aws/templates/eks/control-plane/eks-controlplane-service-webhook.yaml, helm/cluster-api-provider-aws/templates/eks/control-plane/eks-controlplane-service.yaml, helm/cluster-api-provider-aws/templates/infrastructure-deployment.yaml, helm/cluster-api-provider-aws/templates/infrastructure-service.yaml, helm/cluster-api-provider-aws/templates/webhook/deployment.yaml, helm/cluster-api-provider-aws/templates/webhook/service.yaml
=> Fix match labels to be unique for all deployments and services

CHANGELOG.md, helm/cluster-api-provider-aws/templates/_helpers.tpl
=> Fix selector labels for EKS webhook

CHANGELOG.md, Makefile.custom.mk
=> Fix CRD path

CHANGELOG.md, config/helm/kustomization.yaml, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1alpha3/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1alpha4/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta1/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta1/awsclusters.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta1/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta1/awsmachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta1/awsmachines.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta1/awsmachinetemplates.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta1/awsmanagedmachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/templates/apps_v1_deployment_capa-controller-manager.yaml, helm/cluster-api-provider-aws/values.yaml
Signed-off-by: Marcus Noble <github@marcusnoble.co.uk>
=> Bumped to v1.5.0

config/helm/kustomization.yaml, helm/cluster-api-provider-aws/templates/apps_v1_deployment_capa-controller-manager.yaml
Signed-off-by: Marcus Noble <github@marcusnoble.co.uk>
=> Fix linewrap

CHANGELOG.md, helm/cluster-api-provider-aws/templates/_helpers.tpl
=> Keep crd-install Job when it fails

CHANGELOG.md, config/helm/crd_clusterctl_labels.yaml, config/helm/kustomization.yaml, helm/cluster-api-provider-aws/files/bootstrap/bases/eksconfigs.bootstrap.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/bootstrap/bases/eksconfigtemplates.bootstrap.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/controlplane/bases/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsclustercontrolleridentities.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsclusterroleidentities.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsclusters.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsclusterstaticidentities.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsfargateprofiles.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsmachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsmachines.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsmachinetemplates.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsmanagedmachinepools.infrastructure.cluster.x-k8s.io.yaml
Towards https://github.com/giantswarm/giantswarm/issues/23855
=> Add clusterctl labels to CRDs to support `clusterctl move`

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
Fixes https://github.com/giantswarm/roadmap/issues/1609
=> Bump image to v1.5.2-gs

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
Co-authored-by: Jose Armesto <github@armesto.net>
=> Use image built from fork

CHANGELOG.md, config/helm/deployment-args.yaml
=> enable garbage collector

CHANGELOG.md, helm/cluster-api-provider-aws/Chart.yaml
=> Set Helm chart ownership to team hydra

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
Signed-off-by: Marcus Noble <github@marcusnoble.co.uk>
=> Bump to latest release-1.5 changes

config/helm/deployment-args.yaml, helm/cluster-api-provider-aws/templates/apps_v1_deployment_capa-controller-manager.yaml
towards https://github.com/giantswarm/roadmap/issues/996
=> enable-flatcar

CHANGELOG.md, hack/generate-kustomize-patches.sh, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/2215
=> Change default registry from quay to docker

helm/cluster-api-provider-aws/Chart.yaml
=> Switch teams from hydra to phoenix

CHANGELOG.md, helm/cluster-api-provider-aws/files/bootstrap/bases/eksconfigs.bootstrap.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/bootstrap/bases/eksconfigtemplates.bootstrap.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/controlplane/bases/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta1/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta2/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsclustercontrolleridentities.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsclusterroleidentities.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsclusters.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsclusterstaticidentities.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsfargateprofiles.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsmachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsmachines.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsmachinetemplates.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsmanagedclusters.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsmanagedmachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclusters.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/templates/rbac.authorization.k8s.io_v1_clusterrole_capa-manager-role.yaml, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/2351
=> Upgrade CAPA to 2.2.4

CHANGELOG.md, helm/cluster-api-provider-aws/files/copy/psp.yaml, helm/cluster-api-provider-aws/templates/crd-install/crd-psp.yaml, helm/cluster-api-provider-aws/templates/crd-install/crd-rbac.yaml, helm/cluster-api-provider-aws/templates/psp.yaml, helm/cluster-api-provider-aws/values.schema.json, helm/cluster-api-provider-aws/values.yaml
=> add toggle value for PSS migration

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/2929
=> Use `AdditionalTags` for S3 buckets

README.md
Most of this was outdated, and the actually interesting info is already in the CAPA fork's README, so I linked to it instead of trying to repeat information here.
=> Replace README with instructions for IAM setup and working with CAPA fork

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
=> Switch to image hosted on gsoci.azurecr.io

CHANGELOG.md, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta1/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta2/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclusters.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/3015
=> Backport secure VPC default SG change

CHANGELOG.md, helm/cluster-api-provider-aws/templates/crd-install/crd-job.yaml
=> Fix CRD installation job's settings so it can get admitted by Kyverno policies

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
=> Bump capa to latest fork version

CHANGELOG.md, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsmachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsmanagedmachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/27903
=> Add non root volumes to AWSMachinePools

CHANGELOG.md, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsmachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/3442, contains https://github.com/giantswarm/cluster-api-provider-aws/pull/592
=> Support for writing user data to S3 bucket for `AWSMachinePool`

CHANGELOG.md, config/helm/deployment-args.yaml, helm/cluster-api-provider-aws/templates/apps_v1_deployment_capa-controller-manager.yaml
=> Update Sync Period

helm/cluster-api-provider-aws/Chart.yaml
=> Fix appVersion

CHANGELOG.md, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta1/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta2/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclusters.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsmachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsmanagedmachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/31305
=> Add maxHealthyPercentage field

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
=> Filter out AWS internal tags from subnet tags

CHANGELOG.md, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta1/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta2/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta2/rosacontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta1/awsclustercontrolleridentities.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta1/awsclusterroleidentities.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta1/awsclusterstaticidentities.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclustercontrolleridentities.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclusterroleidentities.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclusters.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclusterstaticidentities.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsmachines.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsmachinetemplates.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/rosamachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/templates/apps_v1_deployment_capa-controller-manager.yaml, helm/cluster-api-provider-aws/values.yaml
=> Upgrade to CAPA v2.7.1 + fork changes

CHANGELOG.md, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsmachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsmanagedmachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/31843. Requires https://github.com/giantswarm/giantswarm-aws-account-prerequisites/pull/128 to be applied.
=> Support EC2 lifecycle hooks for machine pools

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/32537
=> Only manage security groups for ENIs tagged by CAPA

CHANGELOG.md, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta1/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta2/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclusters.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/values.yaml
=> Support additional security group ingress rules for all nodes

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/32640
=> Add karpenter IAM Roles to the S3 bucket policy so that karpenter nodes can read userdata

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
=> Bring backports from fork

CHANGELOG.md, helm/cluster-api-provider-aws/Chart.yaml, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/33300
=> Don't overwrite subnet spec tags with AWS tags

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
=> Launchtemplate needs to be updated if spot options are changed

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
=> Check control plane version skew before creating new launch template version
