CHANGELOG.md, helm/cluster-api-provider-aws/templates/webhook/deployment.yaml
We found that if the flag is activated for the aws webhook, it can cause a connection error trying to apply EKS CRs.
=> Deactivate eks flag only for core aws webhook

CHANGELOG.md, helm/cluster-api-provider-aws/templates/eks/bootstrap/eks-bootstrap-deployment-webhook.yaml, helm/cluster-api-provider-aws/templates/eks/bootstrap/eks-bootstrap-deployment.yaml, helm/cluster-api-provider-aws/templates/eks/bootstrap/eks-bootstrap-service-webhook.yaml, helm/cluster-api-provider-aws/templates/eks/bootstrap/eks-bootstrap-service.yaml, helm/cluster-api-provider-aws/templates/eks/control-plane/eks-controlplane-deployment-webhook.yaml, helm/cluster-api-provider-aws/templates/eks/control-plane/eks-controlplane-deployment.yaml, helm/cluster-api-provider-aws/templates/eks/control-plane/eks-controlplane-service-webhook.yaml, helm/cluster-api-provider-aws/templates/eks/control-plane/eks-controlplane-service.yaml, helm/cluster-api-provider-aws/templates/infrastructure-deployment.yaml, helm/cluster-api-provider-aws/templates/infrastructure-service.yaml, helm/cluster-api-provider-aws/templates/webhook/deployment.yaml, helm/cluster-api-provider-aws/templates/webhook/networkpolicy.yaml, helm/cluster-api-provider-aws/templates/webhook/service.yaml
clean the label mess that had several components using same labels for services and deployment causing that some services routed to multiple different components and also some deployment were bugged due thinking that it has running pods
=> fix all labels to be unique for each pod and service

.github/workflows/verify.yaml, CHANGELOG.md, Makefile.custom.mk, hack/generate-kustomize-patches.sh, helm/cluster-api-provider-aws/templates/apps_v1_deployment_capa-controller-manager.yaml
We forgot to re-generate the helm chart when [we added the feature flag](https://github.com/giantswarm/cluster-api-provider-aws-app/pull/138). The generation is broken while we target our fork image, so I re-generated the helm chart using 1.5.2 from upstream.
I also
- Added `verify` github action so we don't forget to generate. It will fail until we go back to use upstream releases.
- Make `curl` to fail if it gets a 404 from Github.
=> Generate manifests for release 1.5.2

CHANGELOG.md, config/helm/common-labels.yaml, helm/cluster-api-provider-aws/templates/apps_v1_deployment_capa-controller-manager.yaml
Hubble would otherwise show "Unknown app" for the flow diagram. Part of https://github.com/giantswarm/giantswarm/issues/27266.
=> Add common labels to pods so that Hubble shows the app name

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/2929
=> Bump to CAPA version with the backported feature "Tag S3 bucket as owned by cluster"

helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta1/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta2/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclusters.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsmachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsmachines.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsmachinetemplates.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsmanagedmachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/templates/rbac.authorization.k8s.io_v1_clusterrole_capa-manager-role.yaml, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/2870, namely the first step of the [suggested migration](https://github.com/giantswarm/roadmap/issues/2870#issuecomment-1827869770).
Note that since the old CRDs are used here, avoiding that the subnet `id` field is required for now, the `make verify` CI job is failing. That must be accepted until step two (update to actual, latest CRDs which make the field required).
See related cluster app changes:
- https://github.com/giantswarm/cluster-aws/pull/439
- https://github.com/giantswarm/cluster-eks/pull/43
=> Upgrade CAPA to v2.3.0 but comment out CRD upgrade so existing clusters reconcile fine without having the newly-required subent `id` field yet

CHANGELOG.md, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta1/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta2/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclusters.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml
Towards https://github.com/giantswarm/roadmap/issues/2870, step 2 of the smooth-ish migration (see https://github.com/giantswarm/roadmap/issues/2870#issuecomment-1827869770).
This must only be merged once MCs/WCs (CAPA EC2/EKS) have been upgraded i.e. after https://github.com/giantswarm/cluster-api-provider-aws-app/pull/193, https://github.com/giantswarm/cluster-aws/pull/439, https://github.com/giantswarm/cluster-eks/pull/43. But we can review already.
=> Upgrade CAPA CRDs to v2.3.0 including required subnet `id` field

CHANGELOG.md, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta1/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta2/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclusters.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml
Towards https://github.com/giantswarm/roadmap/issues/3048. Until we fixed the actual issue upstream, we're going back to expected-working state of app version v2.7.1.
=> Revert CRDs upgrade since CAPA creates unlimited VPCs for EKS clusters because the subnet `id` field cannot be set

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
https://github.com/giantswarm/roadmap/issues/2217
Tested with latest cluster-aws and cluster-eks (WC creation and deletion). Each of the features worked fine in my test, including bootstrap config reference change (requires cluster-aws change https://github.com/giantswarm/cluster-aws/pull/457 which I'll finish later).
=> Backported fixes and features for CAPA v2.3.x

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
https://github.com/giantswarm/roadmap/issues/3048, contains https://github.com/giantswarm/cluster-api-provider-aws/pull/580
Already tested with EC2/EKS workload cluster creation and deletion.
After this, I can fix the subnet `id` field problem and update CRDs accordingly. Until then, the `make verify` action will still fail on purpose (see comments in there).
=> More backported fixes and features for CAPA v2.3.x

CHANGELOG.md, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta1/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta2/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclusters.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml
https://github.com/giantswarm/roadmap/issues/2870
Back in again. This even worked fine with EKS WC creation. And even if it didn't work, EKS cluster creation is now safer after https://github.com/giantswarm/roadmap/issues/3048. EC2 cluster creation and deletion also works fine.
This change is only from `make generate`.
=> Update CRDs to make the subnet `id` field required again

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
bump custom image with the fix for EKS  clusters to remove aws-cni
=> release-2-3-0-gs-ba007f823

CHANGELOG.md, config/helm/kustomization.yaml, helm/cluster-api-provider-aws/templates/apps_v1_deployment_capa-controller-manager.yaml, helm/cluster-api-provider-aws/templates/crd-install/crd-job.yaml, helm/cluster-api-provider-aws/values.yaml
towards https://github.com/giantswarm/roadmap/issues/3254
align registry helm value with `config` repo to be able reuse  it and deploy to China
also add a registry domain for CRD install job
=> change-values-to-use-registry-from-config-repo

CHANGELOG.md, config/helm/deployment-toleration.yaml, config/helm/kustomization.yaml, helm/cluster-api-provider-aws/templates/apps_v1_deployment_capa-controller-manager.yaml
towards https://github.com/giantswarm/giantswarm/issues/30433
- Add toleration for `node.cluster.x-k8s.io/uninitialized` taint.
- Remove toleration for old `node-role.kubernetes.io/master` taint.
=> add-toleration-for-unitialized-nodes

CHANGELOG.md, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta1/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta2/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclusters.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/2563
Includes only https://github.com/giantswarm/cluster-api-provider-aws/pull/590 – needed to select the correct subnets for nodes vs. pods when using a secondary VPC CIDR (such as when using the Cilium ENI mode feature).
=> Support adding custom secondary VPC CIDR blocks in `AWSCluster` (backport)

CHANGELOG.md, helm/cluster-api-provider-aws/files/copy/service-monitor.yaml, helm/cluster-api-provider-aws/templates/service-monitor.yaml, helm/cluster-api-provider-aws/values.schema.json, helm/cluster-api-provider-aws/values.yaml
This PR makes the ServiceMonitor introduced with https://github.com/giantswarm/cluster-api-provider-aws-app/pull/225 optional.
It is still enabled by default, but it can be disabled through the helm value `serviceMonitor.enabled=false`.
This is necessary for example in mc-bootstrap, where the initial bootstrapping vcluster does not have the ServiceMonitor CRD (and we certainly don't want prometheus there).
=> Make ServiceMonitor optional

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/3442
The `tag` must first be filled in after https://github.com/giantswarm/cluster-api-provider-aws/pull/593 is merged and manually tagged. Therefore marking this as draft.
=> Delete machine pool user data files that did not get deleted yet by the lifecycle policy

CHANGELOG.md, helm/cluster-api-provider-aws/values.yaml
=> Tags defined in subnet spec should be applied

CHANGELOG.md, config/helm/crd_webhook.yaml, helm/cluster-api-provider-aws/files/bootstrap/bases/eksconfigs.bootstrap.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/bootstrap/bases/eksconfigtemplates.bootstrap.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/controlplane/bases/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/controlplane/bases/rosacontrolplanes.controlplane.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsclustercontrolleridentities.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsclusterroleidentities.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsclusters.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsclusterstaticidentities.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsfargateprofiles.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsmachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsmachines.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsmachinetemplates.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsmanagedclusters.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/awsmanagedmachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/rosaclusters.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/files/infrastructure/bases/rosamachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/values.yaml
Same as https://github.com/giantswarm/cluster-api-app/pull/283
=> Drop dummy `caBundle` field to support Kubernetes 1.31

CHANGELOG.md, config/helm/deployment-args.yaml, helm/cluster-api-provider-aws/files/infrastructure/patches/versions/v1beta2/awsmachinepools.infrastructure.cluster.x-k8s.io.yaml, helm/cluster-api-provider-aws/templates/apps_v1_deployment_capa-controller-manager.yaml, helm/cluster-api-provider-aws/templates/rbac.authorization.k8s.io_v1_clusterrole_capa-manager-role.yaml, helm/cluster-api-provider-aws/values.schema.json, helm/cluster-api-provider-aws/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/28006
With the feature flag, we want to test this for a short whlie on a test management cluster.
=> Add AWSMachines to back the EC2 instances in AWSMachinePools and AWSManagedMachinePools, add feature gate for this feature (defaults to off)
